In [15]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import warnings; warnings.simplefilter('ignore')
from scipy import stats
from ast import literal_eval
from sklearn.feature_extraction.text import TfidfVectorizer, CountVectorizer
from sklearn.metrics.pairwise import linear_kernel, cosine_similarity
from nltk.stem.snowball import SnowballStemmer
from nltk.stem.wordnet import WordNetLemmatizer
from nltk.corpus import wordnet
from surprise import Reader, Dataset, SVD
from surprise.model_selection import cross_validate

In [75]:
class hybrid(object):
    
    def __init__ (self,user_id,ratings):
        
        self.user_id = user_id
        self.md = pd.read_csv('dataset/processed/FinalData.csv')
        self.ratings = ratings
        self.res=None
        print(ratings)
        print(ratings[(ratings['user_id'] == user_id)][['user_id','book_id', 'rating']])
        print('STARTING CONTENT')
        self.content_rating = self.content_based(self.md,self.ratings,self.user_id)
        print('STARTING POPULARITY')
        self.popularity_rating = self.popularity(self.md)
        print('STARTING COLABORATIVE')
        self.collaborative_rating = self.collaborative(self.ratings, self.user_id)
        print('STARTING HYBRID')
        self.final_hybrid(self.md, self.popularity_rating , self.collaborative_rating, self.content_rating, self.user_id)
        
        
    #Popularity#

    def popularity(self,md):


        fd = pd.read_csv('dataset/processed/AverageRatings.csv')
        fd1 = pd.read_csv('dataset/processed/RatingsCount.csv')
	
        fd[fd['rating'].notnull()]['rating'] = fd[fd['rating'].notnull()]['rating'].astype('float')
        vote_averages= fd[fd['rating'].notnull()]['rating'] 
        C = vote_averages.mean()


        fd1[fd1['rating'].notnull()]['rating'] = fd1[fd1['rating'].notnull()]['rating'].astype('float')
        vote_counts = fd1[fd1['rating'].notnull()]['rating']
        m = len(vote_counts)

        md['ratings_count'] = fd1['rating']
        md['average_rating'] = fd['rating']

        qualified = md[(md['ratings_count'].notnull())][['book_id','title', 'authors', 'ratings_count', 'average_rating']]

        qualified['ratings_count'] = qualified['ratings_count'].astype('float')

        qualified['average_rating'] = qualified['average_rating'].astype('float')

        qualified.shape

        def weighted_rating(x):
            v = x['ratings_count']
            R = x['average_rating']
            return (v/(v+m) * R) + (m/(m+v) * C)

        qualified['popularity_rating'] = qualified.apply(weighted_rating, axis=1)
        pop = qualified[['book_id','popularity_rating']]
        print(qualified.shape)
        print(pop.shape)

        return pop
    ### Collaborative ##

    def collaborative(self,ratings,user_id):

        reader = Reader()
        #ratings.head()

        temp_ratings = ratings



        data = Dataset.load_from_df(temp_ratings[['user_id', 'book_id', 'rating']], reader)
#         data.split(n_folds=2)

        ## Training the data ##
        svd = SVD()
#         evaluate(svd, data, measures=['RMSE', 'MAE'])
        cross_validate(svd, data, measures=['RMSE', 'MAE'])

        trainset = data.build_full_trainset()

        algo = SVD()
        algo.fit(trainset)

        #svd.train(trainset)
        ## Testing the data ##

        from collections import defaultdict
        testset = trainset.build_anti_testset()
        predictions = algo.test(testset)

        count = 0
     
        for uid, iid, true_r, est, _ in predictions:

             if uid == user_id:
                count = count+1
                temp_ratings.loc[len(temp_ratings)+1]= [uid,iid,est]

        #print("count\n")
        #print(count)
        #print("\n--------here-------\n")	
        #print(temp_ratings)

        cb = temp_ratings[(temp_ratings['user_id'] == user_id)][['book_id', 'rating']]
        #print("\n--------here-------\n")
        #print(cb)
        
        cb = temp_ratings[(temp_ratings['user_id'] == user_id)][['book_id', 'rating']]

        return(cb)


    ##### CONTENT ######

    def content_based(self,md,ratings,user_id):       

        md['book_id'] = md['book_id'].astype('str')
        md['year'] = md['year'].astype('str')
        ratings['book_id'] = ratings['book_id'].astype('str')
        ratings['user_id'] = ratings['user_id'].astype('int')
        ratings['rating'] = ratings['rating'].astype('int')
        md['authors'] = md['authors'].str.replace(' ','')
        md['authors'] = md['authors'].str.lower()
        md['authors'] = md['authors'].str.replace(',',' ')
        md['authors'] = md['authors'].apply(lambda x: [x])
        md['publisher'] = md['publisher'].str.replace(' ','')
        md['publisher'] = md['publisher'].str.lower()
        md['publisher'] = md['publisher'].apply(lambda x: [x])
        md['year'] = md['year'].apply(lambda x: [x])
        md['soup'] = md['authors'] + md['year'] + md['publisher']

        md['soup'] = md['soup'].str.join(' ')
        #print('MD_SOUP',md['soup'])
        count = CountVectorizer(analyzer='word',ngram_range=(1,1),min_df=0, stop_words='english') 
        #how it works? add more attrs
        count_matrix = count.fit_transform(md['soup'].values.astype('U'))
        #print('CM',count_matrix.shape)
        cosine_sim = cosine_similarity(count_matrix, count_matrix)
        #print('CS',cosine_sim.shape)

        def build_user_profiles():
            user_profiles=np.full((278858 ,1000),np.nan)
            for i in range(0,45000):
                u=ratings.iloc[i]['user_id']
                b=ratings.iloc[i]['book_id']
                b2=self.md.index[self.md['book_id'] == b].tolist()[0]
                #b2 is id of book in book attrs table md
                user_profiles[u][b2-1]=ratings.iloc[i]['rating']
                
            return user_profiles

        user_profiles=build_user_profiles()
        print('profiles done')

        def _get_similar_items_to_user_profile(person_id):
            #Computes the cosine similarity between the user profile and all item profiles

            user_ratings = np.empty((1000,1))
            for i in range(0,999):
                book_sim=cosine_sim[i] #how book is similar to all others
                user_sim=user_profiles[person_id] #user all book ratings
                user_sim_bool = [x is not np.nan for x in user_sim]
                user_sim=np.nan_to_num(user_sim)
                non_zero_sim_sum = book_sim.dot(user_sim_bool)
                user_ratings[i]=(book_sim.dot(user_sim))/non_zero_sim_sum
                #print('URi', user_ratings[i], book_sim, user_sim, non_zero_sim_sum)
                #similarities*ratings/similarities sum = avg rating

            return user_ratings

        content_ratings = _get_similar_items_to_user_profile(user_id)
        num = md[['book_id']]
        num1 = pd.DataFrame(data=content_ratings[0:,0:])
        frames = [num, num1]

        content_rating = pd.concat(frames, axis =1,join_axes=[num.index])
        content_rating.columns=['book_id', 'content_rating']
        #print('CR', content_ratings)

        return(content_rating)

    
    def final_hybrid(self,md, popularity_rating , collaborative_rating, content_rating, user_id):

        hyb = md[['book_id']]
        title = md[['book_id','title', 'year']]

        hyb = hyb.merge(title,on = 'book_id')
        hyb = hyb.merge(self.collaborative_rating,on = 'book_id')
        hyb = hyb.merge(self.popularity_rating, on='book_id')
        hyb = hyb.merge(self.content_rating, on='book_id')

        def weighted_rating(x):
            v = x['rating']
            R = x['popularity_rating']
            c = x['content_rating']
            return 0.4*v + 0.2*R + 0.4 * c


        hyb['hyb_rating'] = hyb.apply(weighted_rating, axis=1)
        hyb = hyb.sort_values('hyb_rating', ascending=False).head(999)
        hyb.columns = ['Book ID' , 'Title', 'year', 'Collaborative Rating', 'Popularity Rating' , 'Content Rating', 'Hybrid Rating']
        self.res=hyb
        print(len(hyb['Hybrid Rating']))
        print(hyb)

In [94]:
ratings = pd.read_csv('dataset/processed/FinalRatings.csv')[0:45000]
userId=11676
print('\n----------------Results for'+str(userId)+'-------------------')
h = hybrid(userId,ratings)

----------------Results for276796-------------------

In [102]:
ratings['c']=1
ratings.groupby(['user_id']).sum().sort_values(by=['c'])

         rating    c
user_id
2             0    1
146259        0    1
146298        0    1
146310        0    1
146319       10    1
...         ...  ...
153662      190   94
76352        33   96
16795       377  108
35859       180  133
11676      1507  310

[16695 rows x 2 columns]

## RESULTS

In [79]:
h.res.head(40)

,Book ID,Title,year,Collaborative Rating,Popularity Rating,Content Rating,Hybrid Rating
205,0316693006,Four Blind Mice,[2002],5.000000,2.943604,5.0,4.588721
263,0064472264,"On the Bright Side, I'm Now the Girlfriend of ...",[2002],5.000000,2.943586,5.0,4.588717
487,0805063897,Nickel and Dimed: On (Not) Getting By in America,[2002],4.698160,2.943584,5.0,4.467981
878,1573229571,About a Boy (Movie Tie-In),[2002],4.673583,2.943586,5.0,4.458150
246,0151008116,Life of Pi,[2002],4.540389,2.943586,5.0,4.404873
187,3257233051,Veronika Deschliesst Zu Sterben / Vernika Deci...,[2002],4.526238,2.943569,5.0,4.399209
788,0316693200,2nd Chance,[2002],4.507573,2.943586,5.0,4.391746
300,156971620X,Harlequin Valentine,[2002],4.507346,2.943586,5.0,4.391656
791,0399148582,You Cannot Be Serious,[2002],4.506712,2.943607,5.0,4.391406
253,006102063X,Moving Pictures (Discworld Novels (Paperback)),[2002],4.463219,2.943586,5.0,4.374005
299,1563898586,"The League of Extraordinary Gentlemen, Vol. 1",[2002],4.431125,2.943586,5.0,4.361167
566,0451202341,Back Roads,[2001],4.423543,2.943610,5.0,4.358139
784,0670031046,In This Mountain,[2002],4.398892,2.943616,5.0,4.348280
408,0316666343,The Lovely Bones: A Novel,[2002],4.347092,2.943569,5.0,4.327551
819,2253063339,Les Fourmis,[2002],4.346679,2.943586,5.0,4.327389
582,0553107305,Chopping Spree,[2002],4.317169,2.943586,5.0,4.315585
734,207053880X,L'Homme Qui Plantait Des Arbres,[2002],4.265186,2.943578,5.0,4.294790
925,0451155750,The Dead Zone,[2004],4.247647,2.943586,5.0,4.287776
254,0060013117,Night Watch,[2002],4.234661,2.943616,5.0,4.282588
776,0446531332,Nights in Rodanthe,[2002],4.215549,2.943598,5.0,4.274939
177,3257203659,Der illustrierte Mann. ErzÃ?Â¤hlungen.,[2002],4.213730,2.943595,5.0,4.274211
38,0449005615,Seabiscuit: An American Legend,[2002],4.196493,2.943578,5.0,4.267313
319,0972044205,The Breach,[2002],4.177259,2.943601,5.0,4.259624
586,0515134279,The Straw Men,[2002],4.169418,2.943622,5.0,4.256492
541,0312278586,The Nanny Diaries: A Novel,[2002],4.159793,2.943586,5.0,4.252634
348,0771076002,Remembering Peter Gzowski : A Book of Tributes,[2002],4.078091,2.943586,5.0,4.219954
32,3404921038,Wie Barney es sieht.,[2002],4.024476,2.943610,5.0,4.198512
227,0449006522,Manhattan Hunt Club,[2002],3.932518,2.943610,5.0,4.161729
763,0743206045,Daddy's Little Girl,[2002],3.898185,2.943613,5.0,4.147997
593,0451195663,Primal Scream,[1998],3.847660,2.943578,5.0,4.127780
274,037582345X,"The Golden Compass (His Dark Materials, Book 1)",[2002],3.804975,2.943607,5.0,4.110712
926,0786890436,The Diary of Ellen Rimbauer: My Life at Rose Red,[2002],3.791098,2.943586,5.0,4.105157
149,0451525221,Scarlet Letter,[1993],3.782892,2.943586,5.0,4.101874
165,0451206673,Pen Pals,[2002],3.780972,2.943586,5.0,4.101106
529,0451523318,Turn of the Screw and Short N,[1978],3.724943,2.943595,5.0,4.078696
690,0618231617,Almost: A Novel,[2002],3.702875,2.943619,5.0,4.069874
237,0671027387,Deception Point,[2002],3.699975,2.943607,5.0,4.068712
824,0571209521,Terrible Times (Eddie Dickens Trilogy S.),[2002],3.683091,2.943578,5.0,4.061952
275,0375823468,"The Subtle Knife (His Dark Materials, Book 2)",[2002],3.664700,2.943578,5.0,4.054596
731,2070417743,Chroniques martiennes,[2002],3.664327,2.943616,5.0,4.054454